// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
double test();
RcppExport SEXP _nloptr_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _nloptr_test2();
RcppExport SEXP NLoptR_Optimize(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_nloptr_test", (DL_FUNC) &_nloptr_test, 0},
    {"_nloptr_test2",   (DL_FUNC) &_nloptr_test2,   0},
    {"NLoptR_Optimize", (DL_FUNC) &NLoptR_Optimize, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_nloptr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
