# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test2 <- function() {
    .Call('_nloptr_test2', PACKAGE = 'nloptr')
}

test <- function(a) {
    .Call('_nloptr_test', PACKAGE = 'nloptr', a)
}

